#!/bin/sh
#
# @name TB2 Fixed Wing Aircraft
#
# @type Plane A-Tail
# @class Plane
#
# @output Motor1 throttle
# @output Servo1 aileron right
# @output Servo2 aileron left
# @output Servo3 v-tail right
# @output Servo4 v-tail left
# @output Servo5 wheel
# @output Servo6 flaps right
# @output Servo7 flaps left
#
# @maintainer Alireza Ghaderi @alireza787b <p30planets@gmail.com>
#
#

. ${R}etc/init.d/rc.fw_defaults

param set-default FW_MAN_P_MAX 55
param set-default FW_MAN_R_MAX 55
param set-default FW_R_LIM 55

param set-default FW_WR_FF 0.2
param set-default FW_WR_I 0.2
param set-default FW_WR_IMAX 0.8
param set-default FW_WR_P 1
param set-default FW_W_RMAX 0

param set-default CA_AIRFRAME 1
param set-default CA_ROTOR_COUNT 1
param set-default CA_SV_CS_COUNT 7
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TYPE 1 #left aileron
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TYPE 2 #right aileron
param set-default CA_SV_CS2_TRQ_P 0.5
param set-default CA_SV_CS2_TRQ_Y -0.5
param set-default CA_SV_CS2_TYPE 13 #left V-tail
param set-default CA_SV_CS3_TRQ_P 0.5
param set-default CA_SV_CS3_TRQ_Y 0.5
param set-default CA_SV_CS3_TYPE 14 #right V-tail
param set-default CA_SV_CS4_TRQ_Y 1
param set-default CA_SV_CS4_TYPE 12 #wheel
param set-default CA_SV_CS5_TYPE 9 #left flap
param set-default CA_SV_CS6_TYPE 10 #right flap
param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 202
param set-default PWM_MAIN_FUNC3 203
param set-default PWM_MAIN_FUNC4 204
param set-default PWM_MAIN_FUNC5 101
param set-default PWM_MAIN_FUNC6 205
param set-default PWM_MAIN_FUNC7 206
param set-default PWM_MAIN_FUNC8 207



